services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app
          ignore:
            - ./backend/.venv
            - .venv
        - path: ./backend/pyproject.toml
          action: rebuild

  frontend:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "3000:80"
    develop:
      watch:
        - path: ./src
          action: sync
          target: /app
